# Generated by Django 4.0.4 on 2022-10-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eia_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(auto_now_add=True, verbose_name='fecha de compra')),
                ('marca', models.CharField(max_length=250)),
                ('machine_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eia_api.machines')),
            ],
        ),
    ]
